# Generated by Django 3.2.6 on 2022-01-13 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionecampionato', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campionato',
            name='max_partecipanti',
            field=models.IntegerField(default=10, verbose_name='Numero massimo partecipanti'),
        ),
    ]
