# Generated by Django 3.2.6 on 2022-01-14 21:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestionecampionato', '0002_campionato_max_partecipanti'),
    ]

    operations = [
        migrations.AddField(
            model_name='campionato',
            name='championship_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Championship Admin'),
        ),
    ]
