# Generated by Django 3.2.6 on 2022-01-15 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionesquadra', '0004_squadra_allenatore'),
        ('gestionecampionato', '0004_alter_campionato_giornata_corrente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gol_squadra', models.IntegerField(default=0)),
                ('squadra', models.ManyToManyField(to='gestionesquadra.Squadra', verbose_name='Squadra')),
            ],
            options={
                'verbose_name_plural': 'Partite',
            },
        ),
    ]
