# Generated by Django 3.2.6 on 2022-01-16 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionecampionato', '0005_partita'),
    ]

    operations = [
        migrations.AddField(
            model_name='partita',
            name='giornata',
            field=models.IntegerField(default=1, verbose_name='Giornata'),
        ),
        migrations.AlterField(
            model_name='partita',
            name='gol_squadra',
            field=models.IntegerField(default=0, verbose_name='Gol'),
        ),
    ]
