# Generated by Django 3.2.6 on 2022-01-16 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionecampionato', '0006_auto_20220117_0027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partita',
            name='gol_squadra',
        ),
        migrations.AddField(
            model_name='partita',
            name='gol_squadra1',
            field=models.IntegerField(default=0, verbose_name='Gol Squadra 1'),
        ),
        migrations.AddField(
            model_name='partita',
            name='gol_squadra2',
            field=models.IntegerField(default=0, verbose_name='Gol Squadra 2'),
        ),
    ]
