# Generated by Django 3.2.6 on 2022-01-18 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionesquadra', '0007_alter_squadra_allenatore'),
        ('gestionecampionato', '0007_auto_20220117_0028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('T', 'Titolari'), ('R', 'Riserve')], default='T', max_length=2, verbose_name='Gruppo (Titolare/Riserva)')),
                ('giocatore', models.ManyToManyField(to='gestionesquadra.Giocatore', verbose_name='Giocatore')),
                ('partita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionecampionato.partita', verbose_name='Partita')),
            ],
        ),
    ]
