# Generated by Django 3.2.6 on 2022-01-18 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionecampionato', '0008_formazione'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formazione',
            name='partita',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formazione', to='gestionecampionato.partita', verbose_name='Partita'),
        ),
    ]
