# Generated by Django 3.2.6 on 2022-01-19 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionesquadra', '0011_auto_20220118_1845'),
        ('gestionecampionato', '0010_auto_20220118_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formazione',
            name='giocatore',
            field=models.ManyToManyField(related_name='giocatore', to='gestionesquadra.Giocatore', verbose_name='Giocatore'),
        ),
    ]
