# Generated by Django 3.2.6 on 2022-01-21 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionesquadra', '0011_auto_20220118_1845'),
        ('gestionecampionato', '0014_alter_formazione_giocatore'),
    ]

    operations = [
        migrations.AddField(
            model_name='formazione',
            name='squadra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formazione', to='gestionesquadra.squadra', verbose_name='Squadra'),
        ),
    ]
