# Generated by Django 3.2.6 on 2022-01-22 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionecampionato', '0018_rename_max_partecipanti_campionato_partecipanti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campionato',
            name='partecipanti',
            field=models.IntegerField(choices=[(6, '6'), (8, '8'), (10, '10')], default=6, verbose_name='Partecipanti'),
        ),
    ]
