# Generated by Django 3.2.6 on 2022-01-24 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionecampionato', '0019_alter_campionato_partecipanti'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_voti', models.CharField(blank=True, max_length=20)),
                ('ruolo', models.CharField(blank=True, max_length=20)),
                ('nome_giocatore', models.CharField(blank=True, max_length=20)),
                ('voto', models.CharField(blank=True, max_length=20)),
                ('gf', models.CharField(blank=True, max_length=20)),
                ('gs', models.CharField(blank=True, max_length=20)),
                ('rp', models.CharField(blank=True, max_length=20)),
                ('rs', models.CharField(blank=True, max_length=20)),
                ('rf', models.CharField(blank=True, max_length=20)),
                ('au', models.CharField(blank=True, max_length=20)),
                ('amm', models.CharField(blank=True, max_length=20)),
                ('esp', models.CharField(blank=True, max_length=20)),
                ('ass', models.CharField(blank=True, max_length=20)),
                ('gdv', models.CharField(blank=True, max_length=20)),
                ('gdp', models.CharField(blank=True, max_length=20)),
                ('giornata', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Voti',
            },
        ),
    ]
