# Generated by Django 3.2.6 on 2022-01-25 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionecampionato', '0020_voto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campionato',
            name='nome_campionato',
            field=models.CharField(max_length=30),
        ),
    ]
