# Generated by Django 3.2.6 on 2022-01-25 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionecampionato', '0021_alter_campionato_nome_campionato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campionato',
            name='nome_campionato',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
