# Generated by Django 3.2.6 on 2022-01-06 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestionecampionato', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Squadra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome squadra')),
                ('campionato', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestionecampionato.campionato', verbose_name='Campionato')),
            ],
            options={
                'verbose_name_plural': 'Squadre',
            },
        ),
    ]
