# Generated by Django 3.2.6 on 2022-01-06 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionesquadra', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Giocatore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome')),
                ('cognome', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cognome')),
                ('id_voti', models.IntegerField(verbose_name='ID Voti Fantacalcio.it')),
                ('squadra', models.ManyToManyField(to='gestionesquadra.Squadra')),
            ],
        ),
    ]
