# Generated by Django 3.2.6 on 2022-01-06 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionecampionato', '0001_initial'),
        ('gestionesquadra', '0002_giocatore'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='giocatore',
            options={'verbose_name_plural': 'Giocatori'},
        ),
        migrations.AlterField(
            model_name='squadra',
            name='campionato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionecampionato.campionato', verbose_name='Campionato'),
        ),
    ]
