# Generated by Django 3.2.6 on 2022-01-13 03:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestionesquadra', '0003_auto_20220106_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='squadra',
            name='allenatore',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Allenatore'),
        ),
    ]
