# Generated by Django 3.2.6 on 2022-01-18 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionesquadra', '0007_alter_squadra_allenatore'),
    ]

    operations = [
        migrations.AddField(
            model_name='giocatore',
            name='quotazione',
            field=models.IntegerField(default=0, verbose_name='Quotazione'),
        ),
        migrations.AddField(
            model_name='giocatore',
            name='tipo',
            field=models.CharField(blank=True, choices=[('P', 'Portiere'), ('D', 'Difensore'), ('C', 'Centrocampista'), ('A', 'Attaccante')], default='T', max_length=1, null=True, verbose_name='Gruppo (Titolare/Riserva)'),
        ),
    ]
