# Generated by Django 3.2.6 on 2022-01-18 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionesquadra', '0008_auto_20220118_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giocatore',
            name='tipo',
            field=models.CharField(blank=True, choices=[('P', 'Portiere'), ('D', 'Difensore'), ('C', 'Centrocampista'), ('A', 'Attaccante')], default='T', max_length=1, null=True, verbose_name='Ruolo'),
        ),
    ]
