# Generated by Django 3.2.6 on 2022-01-18 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionesquadra', '0009_alter_giocatore_tipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='giocatore',
            old_name='tipo',
            new_name='ruolo',
        ),
    ]
