# Generated by Django 3.2.6 on 2022-01-18 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionesquadra', '0010_rename_tipo_giocatore_ruolo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='giocatore',
            old_name='cognome',
            new_name='nome_completo',
        ),
        migrations.RemoveField(
            model_name='giocatore',
            name='nome',
        ),
    ]
