# Generated by Django 3.2.6 on 2022-01-27 00:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestionesquadra', '0011_auto_20220118_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squadra',
            name='allenatore',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='squadra', to=settings.AUTH_USER_MODEL, verbose_name='Allenatore'),
        ),
    ]
