# Generated by Django 3.2.6 on 2022-01-27 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionesquadra', '0012_alter_squadra_allenatore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squadra',
            name='nome',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nome squadra'),
        ),
    ]
