# Generated by Django 3.2.6 on 2022-01-30 10:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionesquadra', '0014_alter_squadra_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squadra',
            name='nome',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_squadra', message='Il nome della squadra deve essere alfanumerico.', regex='^[A-Za-z a-z 0-9]*$')], verbose_name='Nome squadra'),
        ),
    ]
