# Generated by Django 3.2.6 on 2022-01-06 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestioneutenza', '0002_allenatore_championshipadmin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allenatore',
            options={'verbose_name_plural': 'Allenatori'},
        ),
        migrations.AddField(
            model_name='allenatore',
            name='campionati_vinti',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.CreateModel(
            name='Invito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expire_dt', models.DateTimeField()),
                ('codice_invito', models.CharField(max_length=32)),
                ('destinatario', models.CharField(max_length=255, verbose_name='Email destinatario')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creato da')),
            ],
        ),
    ]
