# Generated by Django 3.2.6 on 2022-01-06 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioneutenza', '0003_auto_20220106_1518'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invito',
            options={'verbose_name_plural': 'Inviti'},
        ),
        migrations.AlterField(
            model_name='invito',
            name='expire_dt',
            field=models.DateTimeField(verbose_name='Data e orario di scadenza'),
        ),
    ]
