# Generated by Django 3.2.6 on 2022-01-10 18:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestioneutenza', '0005_profilo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='championshipadmin',
            name='user',
        ),
        migrations.RemoveField(
            model_name='leagueadmin',
            name='user',
        ),
        migrations.AlterField(
            model_name='profilo',
            name='user',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Utente'),
        ),
        migrations.DeleteModel(
            name='Allenatore',
        ),
        migrations.DeleteModel(
            name='ChampionshipAdmin',
        ),
        migrations.DeleteModel(
            name='LeagueAdmin',
        ),
    ]
