# Generated by Django 3.2.6 on 2022-01-13 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionecampionato', '0001_initial'),
        ('gestioneutenza', '0006_auto_20220110_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='invito',
            name='campionato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionecampionato.campionato', verbose_name='Campionato'),
        ),
    ]
