# Generated by Django 3.2.6 on 2022-01-13 19:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestioneutenza', '0007_invito_campionato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilo',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Utente'),
        ),
    ]
