# Generated by Django 3.2.6 on 2022-01-24 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioneutenza', '0008_alter_profilo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invito',
            name='expire_dt',
            field=models.DateField(verbose_name='Data e orario di scadenza'),
        ),
    ]
