# Generated by Django 3.2.6 on 2022-01-25 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioneutenza', '0010_alter_invito_destinatario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invito',
            name='destinatario',
            field=models.EmailField(max_length=255, unique=True, verbose_name='Email destinatario'),
        ),
    ]
