# Generated by Django 3.2.6 on 2022-01-27 00:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestioneutenza', '0011_alter_invito_destinatario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilo',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='profilo', to=settings.AUTH_USER_MODEL, verbose_name='Utente'),
        ),
    ]
